title:
description:      Iacopo Catalano personal website
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //iacopomc.github.io

# Owner/author information
owner:
  name:           Iacopo Catalano
  avatar:         avatar.jpg
  bio:            B.Sc. in Physics. Learning about Machine Learning,
                  Algorithms and Software Engineering one
                  MOOC at a time. Seeking the chance to satisfy
                  my hunger to learn and my desire to achieve.
  email:          iacopomcatalano@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  github: IacopomC
  linkedin: iacopocatalano

# Links to include in top navigation
# For external links add external: true
links:
  - title: about
    url: /about/
  - title: projects
    url: /projects/
  - title: posts
    url: /posts/
  - title: resume
    url: /assets/images/iacopo_catalano_cv.pdf
#   - title: publications
#     url: /publications/

collections:
  projects:
    output: true
  

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Rome
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

minimal_mistakes_skin: dark

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
